global:
  external_labels:
    cluster: "meta"

scrape_configs:
- job_name: node-exporter
  honor_labels: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['localhost:9100']
